packages:
  # 所有 packages 目录下的包
  - 'apps/*'
  - 'packages/*'
  - 'services/*'
  # 排除测试目录
  - '!**/test/**'
  # 排除构建输出目录
  - '!**/dist/**'
  # 排除 node_modules
  - '!**/node_modules/**'
  # 排除 .turbo 缓存目录
  - '!**/.turbo/**'